POST http://localhost:9091/register HTTP/1.1
Content-Type: application/json

{
  "username": "aksh",
  "password": "654321",
  "email": "aksh@gmail.com",
  "name": "Aksh"
}

###

POST http://localhost:9091/login HTTP/1.1
Content-Type: application/json

{
    "email":"aksh@gmail.com",
    "password": "654321"

}

###
GET http://localhost:9091/get_user_and_profile
Content-Type: application/json

{
  "token": "78cc633ea0b4d526bc4918f29e668fe1d27b2441ef76d1ec9a371c88188aae1c"
}

###


POST http://localhost:9091/update_profile_data
Content-Type: application/json

{
    "token": "78cc633ea0b4d526bc4918f29e668fe1d27b2441ef76d1ec9a371c88188aae1c",
    "bio": "Testing Profile Update"


}


###

GET http://localhost:9091/user/get_all_users